### ISSUE TITLE
新版本可以联网但无法过滤流量

### ISSUE THREAD

**Issue by funianshengsheng** [twoone-3/AdGuardHomeForMagisk#4]
机型红米NOTE95 MIUI14 安卓13
![Image_1721605334405](https://github.com/user-attachments/assets/e1a94b94-94e2-46ec-a87f-0d767830462d)
![Image_1721605329696](https://github.com/user-attachments/assets/cc7c6d1e-fc3c-4716-a67c-b295fe261f62)

**Comment by twoone-3** [comment]
检查私人DNS是否关闭

**Comment by funianshengsheng** [comment]
![Image_1721608943391](https://github.com/user-attachments/assets/deccea4e-79cf-45bc-82b8-92c43a4ba731)
![Image_1721608940984](https://github.com/user-attachments/assets/ceaaa18d-50ed-4055-9340-491d1a89a943)
私人dns是关着的

**Comment by twoone-3** [comment]
从图片可以看出有一个名为wmsctrl_nat_OUTPUT的链，将所有tcp连接转发到了另外的地方，尝试将此规则删除，输入
```
iptables -t nat -D OUTPUT 1
```
即可将此链表的第一个规则删除

**Comment by funianshengsheng** [comment]
> 从图片可以看出有一个名为wmsctrl_nat_OUTPUT的链，将所有tcp连接转发到了另外的地方，尝试将此规则删除，输入
> 
> ```
> su -c iptables -t nat -D OUTPUT 1
> ```
> 
> 即可将此链表的第一个规则删除，
> 
> 注意：我并不清楚这个链表是什么创建的，也不知道有什么用，在我之前用miui系统时有出现过，之后我可能会提高ADGUARD的优先级

okok，麻烦您了

**Comment by funianshengsheng** [comment]
模块过滤效果没有正常生效，在我这里，已经经过了上面操作，您再看一下
![Image_1721622783204](https://github.com/user-attachments/assets/59f3eba2-161c-4a3b-97dd-3de7d63886db)
![Image_1721622781457](https://github.com/user-attachments/assets/8bf777f2-f4ce-41fb-a407-b5eab9d2ab89)

https://d3ward.github.io/toolz/adblock.html
https://checkadblock.ru/这两个广告过滤测试网站过滤效果不正常

**Comment by funianshengsheng** [comment]
> ![Screenshot_20240722-125745_Termux](https://private-user-images.githubusercontent.com/62778573/350841480-613fac7f-4fb7-4bd3-849e-7613c2590a52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MjU5ODUsIm5iZiI6MTcyMTYyNTY4NSwicGF0aCI6Ii82Mjc3ODU3My8zNTA4NDE0ODAtNjEzZmFjN2YtNGZiNy00YmQzLTg0OWUtNzYxM2MyNTkwYTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA1MjEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNzU2ODBmN2YwN2ZhYjEwNTY0YjM4YWExNTIzMjg3N2IwYjNmNjJjMGJjMDAzMzlhZmNiMzUzNGQ4ZTY2NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.INdwgi3Hr4U8UVe84AjO7tXSwvweQds8u5emGI8Ug90) 删除似乎没有生效，这是我的iptables数据，你再试试
> 
> ```
> iptables -t nat -D OUTPUT -j wmsctrl_nat_OUTPUT
> ```
> 
> 只要把OUTPUT链中的这个链删除应该就行了

执行了这个命令后还是没能删掉，不知道是什么原因导致的，能否提高一下adgh的优先级

**Comment by twoone-3** [comment]
将apply_iptables.sh最后一行的-A改为-I,然后直接重启试试

**Comment by funianshengsheng** [comment]
> 将apply_iptables.sh最后一行的-A改为-I,然后直接重启试试

只改这个，命令什么的不用执行吗，还是不行，wmsctrl_nat_OUTPUT依然存在，且adgh现在过滤不了了，都显示为0
![2e3a1fac166ca63b](https://github.com/user-attachments/assets/76c3cc87-ea57-4157-b2ed-46648c647e32)
![-16658acd0f2673f9](https://github.com/user-attachments/assets/cf2eaec5-1c2f-49ef-8473-de8e34c35626)
![-4430c2a73bb25d2a](https://github.com/user-attachments/assets/2f0dddb1-fc5a-454a-99e5-93c22b645898)
