### ISSUE TITLE
导致systemui耗电增多，使copilot对地区识别出错

### ISSUE THREAD

**Issue by mingxitang** [twoone-3/AdGuardHomeForMagisk#5]
systemui的cpu占用率高了大约20%，copilot的保命为com.microsoft.copilot

**Comment by twoone-3** [comment]
systemui占用与本模块无关，Copilot请自行更改 上游DNS 服务器

**Comment by mingxitang** [comment]
> systemui占用与本模块无关，Copilot请自行更改 上游DNS 服务器

好的，谢谢

**Comment by twoone-3** [comment]
一般来说，使用国外DNS服务对于这些国外应用是比较好的，但很少有服务因为你的DNS地区就不让你使用
