### ISSUE TITLE
启用iptables后，无法访问部分校园网地址

### ISSUE THREAD

**Issue by Cccc-owo** [twoone-3/AdGuardHomeForMagisk#6]
版本：20241012, 20241030
环境：ColorOS 14 +  KernelSU
如题，无法访问部分校园网地址

下图即尝试连接校园vpn(aTrust)，出现一直连接不上的情况。在禁用模块后就没问题了
![Screenshot_2024-10-30-14-45-25-33_3d74a38940ff3d65fda120f93aaff3e7.png](https://github.com/user-attachments/assets/79093538-d7b3-4538-b325-d5b10f4d00e6)

**Comment by Cccc-owo** [comment]
在/data/adb/agh/bin/AdGuardHome.loh中，注意到有如下日志（有关于校园网域名）：
```log
2024/10/31 00:05:32.791225 [error] dnsproxy: exchange failed upstream=https://1.12.12.12:443/dns-query question=";otrust.******.edu.cn.\tIN\t AAAA" duration=4.536733072s err="requesting https://1.12.12.12:443/dns-query: Get \"https://1.12.12.12:443/dns-query?dns=AAABAAABAAAAAAABBm90cnVzdANvdWMDZWR1AmNuAAAcAAEAACkIAAAAgAAAAA\": read tcp 172.19.0.1:46502->1.12.12.12:443: read: software caused connection abort"
2024/10/31 00:05:32.791747 [error] dnsproxy: exchange failed upstream=https://1.12.12.12:443/dns-query question=";otrust.******.edu.cn.\tIN\t A" duration=4.523469582s err="requesting https://1.12.12.12:443/dns-query: Get \"https://1.12.12.12:443/dns-query?dns=AAABAAABAAAAAAABBm90cnVzdANvdWMDZWR1AmNuAAABAAEAACkIAAAAgAAAAA\": read tcp 172.19.0.1:46502->1.12.12.12:443: read: software caused connection abort"
```

**Comment by twoone-3** [comment]
网络原因，检查这两行日志的前后是否有network is unreachable

Cccc_ ***@***.***> 于 2024年10月31日周四 08:26写道：

**Comment by Cccc-owo** [comment]
> 网络原因，检查这两行日志的前后是否有network is unreachable

重装模块且清除AdGuardHome.log后重启设备，再次尝试连接，我发现又没有出现相关域名了🤔

**Comment by twoone-3** [comment]
DNS Interference: Some VPNs enforce their own DNS servers, and requests to external DNS servers (like 1.12.12.12) might be blocked or re-routed. This could lead to connection issues, especially if the DNS proxy is configured to use a specific upstream server outside of the VPN’s DNS infrastructure.
可能是VPN软件禁止走DoH

**Comment by twoone-3** [comment]
更新新版试试

**Comment by Cccc-owo** [comment]
新版同样有这个问题
而且改dns好像没什么用

**Comment by twoone-3** [comment]
去config.sh将ipv6设为true试试，需要在关注模块的时候改

**Comment by Cccc-owo** [comment]
开启ipv6后确实好了🤔……
